---
- name: Verify variables are set
  assert:
    that: "{{ item }} is defined"
  with_items:
    - erp_build_number
    - erp_squad_environment
    - erp_squad_auth_token

- name: Gather Facts
  setup:

- name: Check for previous run
  stat:
    path: /root/run_erp_suite.stdout.log
  register: tests_run
- name: Verify host is clean
  fail:
    msg: Error - It looks like tests have already run on this host.
  when: tests_run.stat.exists

- name: Package Prerequisites
  apt:
    update_cache: yes
    cache_valid_time: 86400
    pkg: "{{item}}"
  with_items:
    - git
    - python-pip
    - daemon
    - sysstat # for troubleshooting
    - strace # for troubleshooting

- name: Clone test-definitions repository
  git:
    repo: 'https://git.linaro.org/qa/test-definitions.git'
    dest: /root/test-definitions
    version: erp-17.08

- name: Install python prerequisites
  pip:
    requirements: /root/test-definitions/automated/utils/requirements.txt

- name: Install python prerequisites
  pip:
    name: python-slugify

- name: Copy test harness
  template:
    src: run_erp_suite.sh
    dest: /root/run_erp_suite.sh
    mode: 0755

- name: Run ERP test suite
  # daemon --name ensures only one runs at a time
  command: daemon --name=erp_suite --errlog=/root/run_erp_suite.stderr.log --dbglog=/root/run_erp_suite.stdout.log -- /root/run_erp_suite.sh {{erp_build_number}}
  environment:
    SQUAD_AUTH_TOKEN: "{{erp_squad_auth_token}}"
